Refine resetWLAN script

diff --git a/bin/resetWLAN b/bin/resetWLAN
--- a/bin/resetWLAN
+++ b/bin/resetWLAN
@@ -1,10 +1,20 @@
 #!/bin/bash
 
+unamestr=`uname`
+if [[ "$unamestr" != 'Linux' ]]; then
+  echo "[ERROR] Unknown platform."
+  exit 1
+fi
+
+if ! which usbreset; then
+  echo "[ERROR] No usbreset command."
+  exit 1
+fi
+
 if ip addr show wlan0 | grep 'inet '; then
   echo "IP is retrieved"
 else
-  PRODUCT="802.11 bg WLAN"
   echo "No proper IP... going to reset WIFI..."
-  usbreset "${PRODUCT}"
-  printf "\n[$(date)] Reset USB product: ${PRODUCT}\n" >> /dev/shm/.usb_wifi_log
+  usbreset "${1}"
+  printf "\n[$(date)] Reset USB product: ${1}\n" >> /dev/shm/.usb_wifi_log
 fi
